language: c

compiler:
    - gcc
    - clang

env:
    - BUILDTOOL="cmake" BUILDARGS=""
    - BUILDTOOL="cmake" BUILDARGS="-DENABLE_PYTHON3=ON"
    - BUILDTOOL="cmake" BUILDARGS="-DENABLE_GNUTLS=OFF"
    - BUILDTOOL="autotools" BUILDARGS=""
    - BUILDTOOL="autotools" BUILDARGS="--enable-python3"
    - BUILDTOOL="autotools" BUILDARGS="--disable-gnutls"

before_script:
    - echo 'APT::Install-Recommends "false";' | sudo tee -a /etc/apt/apt.conf
    - sudo apt-get update -qq
    - sudo apt-get -y install devscripts equivs python-pip libenchant-dev autopoint asciidoc source-highlight xsltproc docbook-xsl docbook-xml cmake pkg-config libncursesw5-dev gem2deb libperl-dev python-dev python3-dev libaspell-dev liblua5.1-0-dev tcl8.5-dev guile-2.0-dev libcurl4-gnutls-dev libgcrypt11-dev libgnutls-dev zlib1g-dev
    - wget http://weechat.org/files/tests/ubuntu/precise/amd64/libcpputest-dev_3.4-3_amd64.deb
    - sudo dpkg -i libcpputest-dev_3.4-3_amd64.deb
    - sudo pip install msgcheck pylint

script:
    - ./scripts/build.sh
    - msgcheck po/*.po
    - pylint doc/docgen.py

after_success:
    - weechat --help
    - weechat -r "/debug libs;/quit"

matrix:
    fast_finish: true
